- hosts: localhost
  vars:
    distro: "{{ ansible_distribution }}"
    user: "{{ ansible_env.SUDO_USER }}"
    sudo_user: "{{ ansible_env.USER }}"
  connection: local
  become: true
  become_user: "{{ user }}"

  pre_tasks:
    - name: pre-run | check requirements
      tags: always
      package:
        name: "{{ item }}"
        state: latest
      loop:
        - python-psutil
        - python-pip
        - python-setuptools

    - name: Install github module
      ansible.builtin.pip:
        name: github3.py

    - name: Enable Multilib
      replace:
        path: "/etc/pacman.conf"
        regexp: '#\[multilib]\n#Include = \/etc\/pacman.d\/mirrorlist'
        replace: |
          [multilib]
          Include = /etc/pacman.d/mirrorlist
      when: distro == 'Archlinux'

    - name: pacman -Syu
      pacman:
        update_cache: true
        upgrade: true
    - name: Print user
      debug:
        var: sudo_user
    - name: print sudo_user
      debug:
        var: user

- hosts: localhost
  vars:
    home: "/home/{{ ansible_env.SUDO_USER }}"
    user: "{{ ansible_env.SUDO_USER }}"
    ipaddr: "{{ ansible_default_ipv4.address }}"
  tags: arch
  become: true
  become_user: "{{ user }}"
  vars_prompt:
    - name: git_username
      prompt: git config username
      private: false

    - name: git_email
      prompt: git config email
      private: false
  roles:
    - arch
