- name: desktop env | bspwm | install package
  tags: desktop env
  package:
    name: "{{ item }}"
    state: latest
  loop:
    - bspwm
    - sxhkd
    - nitrogen
    - picom
    - sddm
    - rofi
    - polybar
    - xorg
    - arandr
    - dmenu
    - qt5ct
    - qt6ct
    - lxappearance
  notify:
    - give execute permission to files
    - add desk env