- name: drivers |  nvidia
  package:
    name: "{{ item }}"
    state: latest
  loop:
    - nvidia 
    - nvidia-utils 
    - lib32-nvidia-utils 
    - nvidia-settings 
    - vulkan-icd-loader 
    - lib32-vulkan-icd-loader