- name: drivers | install GPU drivers
  package:
    name: "{{ item }}"
    state: latest
  loop:
    - mesa
    - libva-mesa-driver
    - vulkan-mesa-layers
    - xorg-server
    - xorg-xinit
    - xf86-video-nouveau
    - libva-intel-driver
    - vulkan-intel
    - xf86-video-intel