- name: drivers |  open source video drivers
  package:
    name: "{{ item }}"
    state: latest
  loop:
    - intel-media-driver
    - libva-intel-driver
    - libva-mesa-driver
    - mesa
    - vulkan-intel
    - vulkan-nouveau
    - vulkan-radeon
    - xf86-video-ati
    - xf86-video-amdgpu
    - xf86-video-nouveau
    # - xf86-video-vmware
    - xorg-server
    - xorg-xinit