- name: config dns cache
  tags: network, dnsmasq
  lineinfile:
    path: "/etc/dnsmasq.conf"
    regexp: "^#listen-address="
    line: listen-address=::1,127.0.0.1

- name: start dnsmasq
  tags: dnsmasq, service
  service:
    name: dnsmasq
    state: started
    enabled: yes
