- name: enable gdm
  tags: gdm, service
  service:
    name: gdm
    enabled: yes

- name: install pacman update indicator
  become_user: '{{ user }}'
  tags: pacman update indicator, packages, workstation-packages
  shell:
    cmd: yay -S gnome-shell-extension-arch-update --noconfirm

- name: install custom extensions
  become_user: '{{ user }}'
  tags: pacman update indicator, packages, workstation-packages
  shell:
    cmd: yay -S bibata-cursor-theme gnome-shell-extension-clipboard-history gnome-shell-extension-pop-shell-git --noconfirm
# gnome-shell-extension-forge gnome-shell-extension-custom-accent-colors gnome-shell-extension-dash-to-dock gnome-shell-extension-dash-to-panel gnome-shell-extension-gnome-ui-tune gnome-shell-extension-gtk4-desktop-icons-ng gnome-shell-extension-legacy-theme-auto-switcher
- name: enable shell extensions
  become_user: '{{ user }}'
  tags: shell extensions
  shell: 'gnome-extensions enable {{ item }}'
  loop:
    - appindicatorsupport@rgcjonas.gmail.com
  #  - gnome-ui-tune@itstime.tech
    - pop-shell@system76.com
    - forge@jmmaranan.com
    - arch-update@RaphaelRochet
    - clipboard-history@alexsaveau.dev

- name: set shortcuts
  become_user: '{{ user }}'
  tags: command, gsettings, dconf
  shell:
    cmd: 'dconf load / < {{ home }}/.config/dconf/settings.dconf'

- name: set mangohud output
  lineinfile:
    path: '{{ home }}/.config/MangoHud/MangoHud.conf'
    regexp: '^output_folder='
    line: 'output_folder={{ home }}'
