- name: enable gdm
  tags: gdm, service
  service:
    name: gdm
    enabled: yes

- name: install pacman update indicator
  become_user: "{{ user }}"
  tags: pacman update indicator, packages, workstation-packages
  shell:
    cmd: yay -S gnome-shell-extension-arch-update --noconfirm

- name: install custom extensions
  become_user: "{{ user }}"
  tags: pacman update indicator, packages, workstation-packages
  shell:
    cmd: yay -S gnome-shell-extension-custom-accent-colors gnome-shell-extension-dash-to-dock gnome-shell-extension-dash-to-panel gnome-shell-extension-gnome-ui-tune gnome-shell-extension-gtk4-desktop-icons-ng gnome-shell-extension-legacy-theme-auto-switcher bibata-cursor-theme gnome-shell-extension-pop-shell-git --noconfirm

- name: set shortcuts
  become_user: "{{ user }}"
  tags: command, gsettings, dconf
  shell:
    cmd: "dconf load / < {{ home }}/.config/dconf/keyboard-shortcuts"
