- name: enable gdm
  tags: gdm, service
  service:
    name: gdm
    enabled: yes

- name: install pacman update indicator
  become_user: '{{ user }}'
  tags: pacman update indicator, packages, workstation-packages
  shell:
    cmd: yay -S gnome-shell-extension-arch-update --noconfirm

- name: install custom extensions
  become_user: '{{ user }}'
  tags: pacman update indicator, packages, workstation-packages
  shell:
    cmd: yay -S gnome-shell-extension-blur-my-shell bibata-cursor-theme gnome-shell-extension-clipboard-history --noconfirm
- name: enable shell extensions
  become_user: '{{ user }}'
  tags: shell extensions
  shell: 'gnome-extensions enable {{ item }}'
  loop:
    - appindicatorsupport@rgcjonas.gmail.com
    - blur-my-shell@aunetx
    - arch-update@RaphaelRochet
    - clipboard-history@alexsaveau.dev

- name: set shortcuts
  become_user: '{{ user }}'
  tags: command, gsettings, dconf
  shell:
    cmd: 'dconf load / < {{ home }}/.config/dconf/settings.dconf'

- name: set mangohud output
  lineinfile:
    path: '{{ home }}/.config/MangoHud/MangoHud.conf'
    regexp: '^output_folder='
    line: 'output_folder={{ home }}'


- name: install extension-manager
  become_user: "{{ user }}"
  tags: extension-manager, packages, workstation-packages
  shell:
    cmd: yay -S extension-manager --noconfirm