- name: enable lightdm
  service:
    name: lightdm
    enabled: true

- name: config lightdm-greeter
  lineinfile:
    path: "/etc/lightdm/lightdm.conf"
    regexp: "^#greeter-session="
    line: "greeter-session=lightdm-gtk-greeter"

- name: config lightdm-gtk-greeter
  lineinfile:
    path: "/etc/lightdm/lightdm-gtk-greeter.conf"
    line: |
      [greeter]
      theme-name = Adwaita-dark
      icon-theme-name = Adwaita
      background = /usr/share/pixmaps/~
      position = 1%,start 50%,center
      hide-user-image = true
      font-name = FireCode Nerd Font 10
      indicators = ~host;~spacer;~clock;~session;~layout;~power

- name: extract wallpapers
  shell: |
    tar -xzf {{ ansible_env.HOME }}/arch_playbook/wallpapers.tar.gz
    mkdir -p {{ ansible_env.HOME }}/Wallpapers/
    cp -r {{ ansible_env.HOME }}/arch_playbook/walls/* {{ ansible_env.HOME }}/Wallpapers/
    rm -rf {{ ansible_env.HOME }}/arch_playbook/walls
  become_user: "{{ user }}"

- name: set lightdm-gtk-greeter wallpaper
  command: "cp {{ home }}/Wallpapers/copland.png /usr/share/pixmaps/~"

