- name: locales config
  tags: locales, config
  lineinfile:
    path: "/etc/locale.gen"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - { regexp: "^#zh_HK.UTF-8", line: "zh_HK.UTF-8 UTF-8" }
    - { regexp: "^#zh_CN.UTF-8", line: "zh_CN.UTF-8 UTF-8" }
    - { regexp: "^#ko_KR.UTF-8", line: "ko_KR.UTF-8 UTF-8" }
    - { regexp: "^#ja_JP.UTF-8", line: "ja_JP.UTF-8 UTF-8" }
    - { regexp: "^#pt_BR.UTF-8", line: "pt_BR.UTF-8 UTF-8" }
  notify: generate locales

- name: generate locales
  shell:
    cmd: locale-gen
    