- name: start prometheus service
  tags: prometheus, service
  service:
    name: prometheus
    state: started
    enabled: yes

- name: start prometheus-node-exporter service
  tags: prometheus-node-exporter, service
  service:
    name: prometheus-node-exporter
    state: started
    enabled: yes

- name: dynamic set ip in server prometheus.yml
  lineinfile:
    path: /etc/prometheus/prometheus.yml
    regexp: "{{ item.regex }}"
    line: "{{ item.line }}"
    backup: true
  loop:
    - {
        regex: '- targets: \[''localhost:9090''\]',
        line: "      - targets: ['localhost:9090', '{{ ipaddr }}:9090']",
      }
    - {
        regex: '- targets: \[''localhost:9100''\]',
        line: "      - targets: ['localhost:9100', '{{ ipaddr }}:9100']"
      }
  delegate_to: tokyo