- name: set dotfiles
  tags: stow
  become_user: "{{ user }}"
  shell: sh -c "cd ; git clone https://github.com/fabioalmeida08/.dotfiles ; cd .dotfiles ; stow --adopt . ; git restore ."


- name: set xfce4 dotfiles
  tags: stow
  become_user: "{{ user }}"
  shell: sh -c "cd ; git clone https://github.com/fabioalmeida08/.dotfilesxfce4 ; cd .dotfiles ; stow --adopt . ; git restore ."