- name: fonts
  tags: fonts, meslo
  package:
    name: "{{ item }}"
    state: latest
  loop:
    - ttf-meslo-nerd
    - ttf-firacode-nerd
    - ttf-iosevka-nerd
    - ttf-liberation
    - adobe-source-han-sans-jp-fonts
    - adobe-source-han-sans-cn-fonts
    - adobe-source-han-sans-kr-fonts
    - noto-fonts-emoji
