- name: software | qtct | install package
  tags: qtct, packages, workstation-packages
  package:
    name: "{{ item }}"
    state: latest
  loop:
    - qt5ct
    - qt6ct
    - lxappearance
    - adwaita-qt5
    - adwaita-qt6
    - gnome-themes-extra